name: Render and Release

on:
    - push
    - pull_request

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install LaTeX with ModernCV
              run: sudo apt-get update && sudo apt-get install -y texlive-latex-extra texlive-fonts-extra fonts-font-awesome
            - name: Render PDF
              run: pdflatex -jobname "${{ secrets.NAME }}" cv.tex
            - name: Upload CV to Artifact
              uses: actions/upload-artifact@v7
              with:
                  name: CV
                  path: ${{ secrets.NAME }}.pdf

    publish:
        name: publish
        runs-on: ubuntu-latest
        needs: build
        if: ${{ github.ref_type == 'tag' }}
        steps:
            - name: Get Built CV
              uses: actions/download-artifact@v8
              with:
                  name: CV
                  path: ./${{ secrets.NAME }}.pdf
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  draft: false
                  prerelease: false
                  files: ${{ secrets.NAME }}.pdf
